title: Siahaan.
tagline: A logbook for writeups, technically?
description: >-
  Writeups and notes on cyber security and programming by Chrisando Ryan.
url: https://chrisandoryan.github.io
lang: en
timezone: Asia/Jakarta

author:
  name: Chrisando Ryan
  email: ando@questlabs.id
  github: chrisandoryan
  twitter: chrisandoryan
  linkedin: chrisandoryan

google_analytics: G-9WN9SJYRJE

hero_snippet: blackhat-asia-2020

collections:
  tabs:
    output: true
    sort_by: order
  hero:
    output: false

defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
      render_with_liquid: false
  - scope:
      type: hero
    values:
      render_with_liquid: false
  - scope:
      type: tabs
    values:
      layout: page
      permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude:
  - README.md
  - LICENSE
